export const projects = [
  {
    slug: 'whitmore-residence',
    title: 'The Whitmore Residence',
    type: 'Residential',
    location: 'Chennai',
    year: '2024',
    hero: '/images/projects/whitmore-hero.jpg',
    description: 'A family home reimagined as an essay in restraint. Every material chosen for how it ages — travertine, aged brass, hand-trowelled plaster. Light was the primary design element; we spent three months studying how it moved through the site before drawing a single line.',
    area: '4,200 sq ft',
    client: 'Private Residence',
    materials: ['Travertine', 'Aged Brass', 'Hand-trowelled Plaster', 'Jatoba Wood'],
    images: [
      '/images/projects/whitmore-01.jpg',
      '/images/projects/whitmore-02.jpg',
      '/images/projects/whitmore-03.jpg',
      '/images/projects/whitmore-04.jpg',
    ],
  },
  {
    slug: 'atelier-nord',
    title: 'Atelier Nord',
    type: 'Commercial',
    location: 'Bengaluru',
    year: '2024',
    hero: '/images/projects/atelier-hero.jpg',
    description: 'A jewellery atelier conceived as a dark cabinet of curiosities. Display cases become architecture. The collection is the room.',
    area: '1,800 sq ft',
    client: 'Atelier Nord Jewels',
    materials: ['Nero Marquina', 'Blackened Steel', 'Museum Glass', 'Velvet'],
    images: [
      '/images/projects/atelier-01.jpg',
      '/images/projects/atelier-02.jpg',
      '/images/projects/atelier-03.jpg',
    ],
  },
  {
    slug: 'the-bay-apartment',
    title: 'The Bay Apartment',
    type: 'Residential',
    location: 'Mumbai',
    year: '2023',
    hero: '/images/projects/bay-hero.jpg',
    description: 'A high-rise apartment stripped to its bones and rebuilt with craft. The sea was always there; we simply removed everything that competed with it.',
    area: '2,900 sq ft',
    client: 'Private Residence',
    materials: ['Limed Oak', 'Washed Concrete', 'Rattan', 'Linen'],
    images: [
      '/images/projects/bay-01.jpg',
      '/images/projects/bay-02.jpg',
      '/images/projects/bay-03.jpg',
    ],
  },
  {
    slug: 'villa-sereno',
    title: 'Villa Sereno',
    type: 'Residential',
    location: 'Dubai',
    year: '2023',
    hero: '/images/projects/sereno-hero.jpg',
    description: 'A villa in the desert that draws humidity from memory — water features, dense planting, and a palette that cools the eye.',
    area: '8,500 sq ft',
    client: 'Private Residence',
    materials: ['Cream Limestone', 'Teak', 'Bronze', 'Silk'],
    images: [
      '/images/projects/sereno-01.jpg',
      '/images/projects/sereno-02.jpg',
      '/images/projects/sereno-03.jpg',
    ],
  },
  {
    slug: 'the-orisso-hotel',
    title: 'The Orisso Hotel',
    type: 'Hospitality',
    location: 'Chennai',
    year: '2022',
    hero: '/images/projects/orisso-hero.jpg',
    description: 'A boutique hotel in Nungambakkam designed around the Tamil tradition of threshold-making. Every transition between spaces is a ceremony.',
    area: '12,000 sq ft',
    client: 'Orisso Hospitality Group',
    materials: ['Red Oxide', 'Chettinad Tile', 'Teak', 'Handwoven Cotton'],
    images: [
      '/images/projects/orisso-01.jpg',
      '/images/projects/orisso-02.jpg',
      '/images/projects/orisso-03.jpg',
    ],
  },
]

export const products = [
  {
    slug: 'arc-floor-lamp-07',
    name: 'Arc Floor Lamp',
    subtitle: 'No. 07',
    category: 'Lighting',
    price: 124000,
    materials: ['Brass', 'Matte Black', 'Chrome'],
    stock: 3,
    limited: 12,
    isNew: true,
    description: 'Hand-finished brass with a matte interior that diffuses light into a warm ambient glow. Cast in small batches by a foundry in Moradabad. The arc is a single drawn gesture — no welds, no joints.',
    dimensions: 'H 165cm × W 45cm × Base ⌀ 28cm',
    weight: '8.4 kg',
    careInstructions: 'Wipe with a dry cloth. Avoid abrasive cleaners. The brass will develop a natural patina over time — this is encouraged.',
    leadTime: '8–10 weeks',
    images: [
      '/images/products/lamp-07-brass-01.jpg',
      '/images/products/lamp-07-brass-02.jpg',
      '/images/products/lamp-07-brass-03.jpg',
      '/images/products/lamp-07-brass-04.jpg',
    ],
  },
  {
    slug: 'lounge-chair-travertine',
    name: 'Lounge Chair',
    subtitle: 'Travertine Ed.',
    category: 'Seating',
    price: 380000,
    materials: ['Travertine', 'Cream Boucle'],
    stock: 1,
    limited: 6,
    isNew: false,
    description: 'A lounge chair conceived as a landscape. The travertine frame references the geology of ancient quarries; the boucle cushion is the sediment. Edition of 6, signed.',
    dimensions: 'H 82cm × W 76cm × D 80cm. Seat height: 38cm',
    weight: '42 kg',
    careInstructions: 'Stone: seal annually with a penetrating stone sealer. Fabric: dry clean only.',
    leadTime: '12–16 weeks',
    images: [
      '/images/products/chair-travertine-01.jpg',
      '/images/products/chair-travertine-02.jpg',
      '/images/products/chair-travertine-03.jpg',
      '/images/products/chair-travertine-04.jpg',
    ],
  },
  {
    slug: 'console-onyx-01',
    name: 'Onyx Console',
    subtitle: 'No. 01',
    category: 'Tables',
    price: 680000,
    materials: ['Green Onyx', 'Blackened Steel'],
    stock: 2,
    limited: 4,
    isNew: false,
    description: 'A console table that makes no attempt to disappear. The onyx slab is a 40mm section of a single block — each piece has a different internal landscape of light.',
    dimensions: 'H 80cm × W 140cm × D 35cm',
    weight: '95 kg',
    careInstructions: 'Stone: do not place hot objects directly. Clean with pH-neutral soap and water.',
    leadTime: '14–18 weeks',
    images: [
      '/images/products/console-onyx-01.jpg',
      '/images/products/console-onyx-02.jpg',
      '/images/products/console-onyx-03.jpg',
    ],
  },
  {
    slug: 'ceramic-vessel-set',
    name: 'Ceramic Vessel',
    subtitle: 'Set of Three',
    category: 'Objects',
    price: 28000,
    materials: ['Matte White', 'Terracotta', 'Ash Glaze'],
    stock: 8,
    limited: 0,
    isNew: true,
    description: 'Three vessels thrown on a wheel in a Chennai studio. Proportioned to hold a single stem, a cluster, or nothing at all. The imperfections are the work.',
    dimensions: 'Heights: 28cm, 22cm, 15cm',
    weight: '1.2 kg each',
    careInstructions: 'Wipe exterior with a damp cloth. Food-safe glaze. Hand wash only.',
    leadTime: '4–6 weeks',
    images: [
      '/images/products/vessels-01.jpg',
      '/images/products/vessels-02.jpg',
      '/images/products/vessels-03.jpg',
    ],
  },
  {
    slug: 'linen-throw-natural',
    name: 'Handwoven Linen Throw',
    subtitle: 'Natural × Ecru',
    category: 'Textiles',
    price: 18500,
    materials: ['Natural Linen', 'Ecru Cotton'],
    stock: 15,
    limited: 0,
    isNew: false,
    description: 'Woven on a traditional loom in Kanchipuram. The irregular weave catches light differently across its surface. Two colourways only, produced in seasonal runs.',
    dimensions: '160cm × 130cm',
    weight: '0.9 kg',
    careInstructions: 'Machine wash cold, gentle cycle. Dry flat. Slight shrinkage expected — washes in.',
    leadTime: '2–3 weeks',
    images: [
      '/images/products/throw-01.jpg',
      '/images/products/throw-02.jpg',
    ],
  },
  {
    slug: 'wall-sconce-brass-02',
    name: 'Wall Sconce',
    subtitle: 'Brass — No. 02',
    category: 'Lighting',
    price: 42000,
    materials: ['Brass', 'Matte White'],
    stock: 6,
    limited: 20,
    isNew: false,
    description: 'A wall sconce that projects light as architecture. The brass arm rotates 30 degrees, allowing the light to be directed. Sold in pairs — priced individually.',
    dimensions: 'H 28cm × Projection 22cm × Base ⌀ 8cm',
    weight: '1.8 kg',
    careInstructions: 'Wipe with dry cloth. Brass patina is natural and desirable.',
    leadTime: '6–8 weeks',
    images: [
      '/images/products/sconce-02-01.jpg',
      '/images/products/sconce-02-02.jpg',
    ],
  },
]
